title: Shamkhal Hajiyev
logo: /assets/img/ProfilePhoto.png
description: Proficient and adaptable Data Scientist
with expertise in Machine Learning,
Deep Learning, and Econometrics.
I possess a mastery of cloud
services and cutting-edge programming
languages, facilitating seamless multitasking
across projects. Recognized for
my rapid learning ability and exceptional
teamwork, I excel in navigating intricate
environments and driving successful
outcomes with ease and precision.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
